studentBASE/urls.py
import os
from django.conf.urls import patterns, include, url
from studentBASE import views
from django.contrib.auth.decorators import login_required


static = os.path.join(os.path.dirname(__file__), 'static')

urlpatterns = patterns('',
	#url(r'^$', views.MainPage.as_view(), name='index'),
	url(r'^group/$', views.GroupList.as_view(), name='group_list'),
    url(r'^$', views.GroupList.as_view(), name='index'),
	url(r'^group_view/(?P<pk>\d+)/$', views.GroupDetailView.as_view(), name='group_detail'), 
	url(r'^group/add/$', login_required(views.GroupCreate.as_view()), name='group_add'),
	url(r'^group/(?P<pk>\d+)/$', login_required(views.GroupUpdate.as_view()), name='group_update'),
    url(r'^group/(?P<pk>\d+)/delete/$', login_required(views.GroupDelete.as_view()), name='group_delete'),
    url(r'^student/$', views.StudentList.as_view(), name='student_list'),
    url(r'^student/add/$', login_required(views.StudentCreate.as_view()), name='student_add'),
    url(r'^student_view/(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name='student_detail'), 
    url(r'^student/(?P<pk>\d+)/delete/$', login_required(views.StudentDelete.as_view()), name='student_delete'),
    url(r'^student/(?P<pk>\d+)/$', login_required(views.StudentUpdate.as_view()), name='student_update'),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': static}),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout'),
)

studentDB/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studentDB.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('studentBASE.urls')),
)

studentBASE/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete
import datetime
from django.utils import timezone

# Create your models here.

class Student(models.Model):
	first_name = models.CharField(max_length=50)
	second_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)

	birth = models.DateField()
	number = models.IntegerField(unique=True)
	group = models.ForeignKey('Group')

	def __str__(self):
		return self.last_name+ ' ' + self.first_name

	def get_absolute_url(self):
		return '/student_view/' + self.id.__str__() + '/'

class Group(models.Model):
	title = models.CharField(max_length=50)
	cheif = models.ForeignKey(to='Student',unique=True, blank=True, null=True, related_name='cheif')

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return '/group_view/' + self.id.__str__() + '/'

class Signal(models.Model):
	type_signal = models.CharField(max_length=50)
	sender = models.CharField(max_length=50)
	date = models.DateTimeField('date signal')

	def __str__(self):
		return self.sender + ' ' + self.type_signal


@receiver(post_save, sender=Group)
@receiver(post_save, sender=Student)
@receiver(post_delete, sender=Student)
@receiver(post_delete, sender=Group)
def write_action(instance, **kwargs):
	type_signal = ''
	if 'created' in kwargs:
		if kwargs['created'] == True:
			type_signal = 'created'
		else:
			type_signal = 'updated'
	else:
		type_signal = 'deleted'
	signal = Signal(type_signal=type_signal, sender=(instance.__class__).__qualname__,date=timezone.now())
	signal.save()

studentBASE/views.py
from django.shortcuts import render
from django.views.generic.base import View
from studentBASE.models import *
from django.views.generic import ListView
from django.views.generic import DetailView
from django.shortcuts import get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.template import Context, RequestContext
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.

class MainPage(View):
	template_name = 'studentBASE/main.html'
	def get(self, request, *args, **kwargs):
		return render(request, self.template_name)

class GroupList(ListView):
	model = Group
	context_object_name = 'group_list'
	template_name = 'studentBASE/group_list.html'
'''
	def get(self, request, *args, **kwargs):
		group_list = Group.objects.all()
		return render(request, self.template_name, {'group_list': group_list})
'''
class StudentList(ListView):
	model = Student
	context_object_name = 'student_list'

	def get_context_data(self, **kwargs):
		# Call the base implementation first to get a context
		context = super(StudentList, self).get_context_data(**kwargs)
		# Add in a QuerySet of all the books
		#context['student_list'] = Student.objects.all()
		context['show_group_name'] = True
		return context

class GroupDetailView(DetailView):
	model = Group
	context_object_name = 'group'

	def get_context_data(self, **kwargs):
		# Call the base implementation first to get a context
		context = super(GroupDetailView, self).get_context_data(**kwargs)
		# Add in a QuerySet of all the books
		group = get_object_or_404(Group, id=self.kwargs['pk'])
		context['group'] = group
		context['student_list'] = group.student_set.all()
		return context

class GroupCreate(CreateView):
	model = Group

class GroupUpdate(UpdateView):
	model = Group

class GroupDelete(DeleteView):
	model = Group
	success_url = reverse_lazy('group_list')

class StudentCreate(CreateView):
	model = Student
	template_name = 'studentBASE/student_form_custom.html'

	def get(self, request, *args, **kwargs):
		if 'group_id' in request.GET:
			group_id = request.GET['group_id']
			group = Group.objects.get(id=group_id)
			variables = RequestContext(request, {
				'group' : group,
			})
		else:
			variables = RequestContext(request, {})
		return render(request, self.template_name, variables)

class StudentUpdate(UpdateView):
	model = Student

	def get_context_data(self, **kwargs):
		# Call the base implementation first to get a context
		context = super(StudentUpdate, self).get_context_data(**kwargs)
		# Add in a QuerySet of all the books
		group_list = Group.objects.all()
		context['group_list'] = group_list
		return context

class StudentDelete(DeleteView):
	model = Student
	success_url = "/group/"

class StudentDetailView(DetailView):
	model = Student
	context_object_name = 'student'

	def get_object(self):
		return get_object_or_404(Student, id=self.kwargs['pk'])


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect("/")

def login(request):
	if 'username' in request.POST and request.POST['username']:
		u = request.POST['username']
		password = request.POST['password']
		user = auth.authenticate(username=u, password=password)
		if user is not None and user.is_active:
			# Правильный пароль и пользователь "активен"
			auth.login(request, user)
			# Перенаправление на "правильную" страницу
			return HttpResponseRedirect("/")
		else:
			# Отображение страницы с ошибкой
			return HttpResponseRedirect("/login")
    
	return render(request, 'registration/login.html')

studentBASE/templates/studentBASE/base.html
<html debug="true">
	<head>
		<meta charset="utf-8">
    	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
    	<title>StudentsBASE | {% block title %}{% endblock %}</title>

    	{% load staticfiles %}
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/style.css' %}" rel="stylesheet">
    	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    	<!-- Include all compiled plugins (below), or include individual files as needed -->
    	<script src="{% static 'js/bootstrap.min.js' %}"></script>
    	{% block external %}{% endblock %}
	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        	<div class="navbar-header">
          		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              		<span class="sr-only">Toogle navigation</span>
             		<span class="icon-bar"></span>
              		<span class="icon-bar"></span>
              		<span class="icon-bar"></span>
          		</button>
          		<a class="navbar-brand" href="{% url 'index' %}">StudentsBASE</a>
        	</div>
        	{% block menu %}
        	{% endblock %}
    	</nav>
		<h1>{% block head %}{% endblock %}</h1>
		{% block content %}{% endblock %}
		<br/>
		<br/>
	</body>
</html>

studentBASE/templates/studentBASE/edit_link.html
<a href="{{ way }}">way</a>

studentBASE/templates/studentBASE/group_confirm_delete.html
{% extends 'studentBASE/base.html' %}
{% block menu %}
	<div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          	<li class="active"><a href="{% url 'group_list' %}">Groups</a></li>
          	<li><a href="{% url 'student_list' %}">Students</a></li>
            {% if not user.is_authenticated %}
                <li><a href="{% url 'login' %}">Login</a></li>
            {% else %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}
{% block content %}
<div class="container">
	<div class="row">
		<form action="" method="post" class="text-center">{% csrf_token %}
    		<h4>Are you sure you want to delete "{{ object }}"?</h4>
    		<br>
    		<input type="submit" value="Confirm"  class="btn btn-warning" />
		</form>
	</div>
</div>
{% endblock %}

studentBASE/templates/studentBASE/group_detail.html
{% extends 'studentBASE/base.html' %}
{% block menu %}
	<div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          	<li class="active"><a href="{% url 'group_list' %}">Groups</a></li>
          	<li><a href="{% url 'student_list' %}">Students</a></li>
          	{% if not user.is_authenticated %}
                <li><a href="{% url 'login' %}">Login</a></li>
            {% else %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}
{% block content %}
<div class="container">
	<div class="row">
		<h1>{{ group.title }}
			<small>
				<a href="{% url 'group_update' pk=group.id %}">
					[edit]
				</a>
			</small>
			<small>
				<a href="{% url 'group_delete' pk=group.id %}">
					[delete]
				</a>
			</small>
		</h1>
		<h3>Cheif</h3>
		<a href="{% url 'student_detail' pk=group.cheif.id %}">&nbsp;&nbsp;&nbsp;&nbsp;	{{ group.cheif.last_name }} {{ group.cheif.first_name }} {{ group.cheif.second_name }}</a>
		<h3>Students</h3>
		{% include "studentBASE/student_list_partial.html" %}
		<hr>
		<a href="{% url 'student_add' %}?group_id={{ group.id }}" class="btn btn-info">Add student</a>
		<a href="{% url 'group_list' %}" class="btn btn-info">All groups</a>
	</div>
</div>
{% endblock %}

studentBASE/templates/studentBASE/group_form.html
{% extends 'studentBASE/base.html' %}
{% block menu %}
	<div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          	<li class="active"><a href="{% url 'group_list' %}">Groups</a></li>
          	<li><a href="{% url 'student_list' %}">Students</a></li>
          	{% if not user.is_authenticated %}
                <li><a href="{% url 'login' %}">Login</a></li>
            {% else %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}
{% block content %}
<div class="container">
	<div class="row">
		{% if not group %}
			<h1>New group</h1>
		{% else %}
			<h1>Edit group</h1>
		{% endif %}
		<form method='POST' action='' class="form-horizontal">{% csrf_token %}
			<div class="form-group">
					<label for="id_title" class="col-sm-2 control-label">
						Title:
					</label> 
					<div class="col-sm-3">
						<input id="id_title" class="form-control" maxlength="50" name="title" type="text" value="{{ group.title }}" />
					</div>
			</div>
			<div class="form-group">
				<label for="id_cheif" class="col-sm-2 control-label">Cheif:</label> 
				<div class="col-sm-3">
					<select id="id_cheif" name="cheif" class="form-control"  class="col-sm-2 control-label">
						<option value="">---------</option>
						{% if group %}
							{% for student in group.student_set.all %}
								<option  value="{{ student.id }}" {% if group.cheif.id == student.id %}selected="selected"{% endif %} >{{ student.first_name }} {{ student.last_name }}</option>	
							{% endfor %}
						{% endif %}
					</select></p>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
   					<input type='Submit'  class="btn btn-info" value="Save" />
   				</div>
   			</div>
		</form>
	</div>
</div>
{% endblock %}

studentBASE/templates/studentBASE/group_list.html
{% extends 'studentBASE/base.html' %}
{% block menu %}
	<div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          	<li class="active"><a href="{% url 'group_list' %}">Groups</a></li>
          	<li><a href="{% url 'student_list' %}">Students</a></li>
          	{% if not user.is_authenticated %}
                <li><a href="{% url 'login' %}">Login</a></li>
            {% else %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}
{% block content %}
{% load studentBASE_extras %}
<div class="container">
	<div class="row">
		<h2>Groups</h2>
		<table class="table table-hover">
			<thead>
			<tr>
				<th>Group</th>
				<th>Students count</th>
				<th>Cheif</th>
				<th>Link to Admin</th>
			</tr>
		</thead>
			{% for group in group_list %}
				<tr>
					<td>
						<a href="{% url 'group_detail' pk=group.id %}">{{ group.title }}</a>
					</td>
					<td>
						{{ group.student_set.count }}
					</td>
					<td>
						{{group.cheif }}
					</td>
					<td>
						<a href="{% edit group %}">[To Admin]</a>
					</td>
				</tr>
			{% endfor %}
		</table>
		<a href="{% url 'group_add' %}" class="btn btn-info">New</a>
	</div>
</div>
{% endblock %}

studentBASE/templates/studentBASE/main.html
{% extends 'studentBASE/base.html' %}
{% block menu %}
	<div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          	<li class="active"><a href="{% url 'index' %}">Main</a></li>
          	<li><a href="{% url 'group_list' %}">Groups</a></li>
          	<li><a href="{% url 'student_list' %}">Students</a></li>
        </ul>
    </div>
{% endblock %}
{% block content %}
<a href="{% url 'group_list' %}">Groups</a>
{% endblock %}

studentBASE/templates/studentBASE/student_confirm_delete.html
{% extends 'studentBASE/base.html' %}
{% block menu %}
	<div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          	<li><a href="{% url 'group_list' %}">Groups</a></li>
          	<li class="active"><a href="{% url 'student_list' %}">Students</a></li>
            {% if not user.is_authenticated %}
                <li><a href="{% url 'login' %}">Login</a></li>
            {% else %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}
{% block content %}
<div class="container">
	<div class="row">
		<form action="" method="post" class="text-center">{% csrf_token %}
    		<h4>Are you sure you want to delete "{{ object }}"?</h4>
    		<br>
    		<input type="submit" value="Confirm"  class="btn btn-warning" />
		</form>
	</div>
</div>
{% endblock %}

studentBASE/templates/studentBASE/student_detail.html
{% extends 'studentBASE/base.html' %}
{% block menu %}
	<div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          	<li><a href="{% url 'group_list' %}">Groups</a></li>
          	<li class="active"><a href="{% url 'student_list' %}">Students</a></li>
            {% if not user.is_authenticated %}
                <li><a href="{% url 'login' %}">Login</a></li>
            {% else %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}
{% block content %}
<div class="container">
	<div class="row">
		<h3>Student<small>
				<a href="{% url 'student_update' pk=student.id %}">
					[edit]
				</a>
			</small>
			<small>
				<a href="{% url 'student_delete' pk=student.id %}">
					[delete]
				</a>
			</small>
		</h3>
		<form class="form-horizontal" role="form">
  			<div class="form-group">
    			<label class="col-sm-2 control-label">First name</label>
    			<div class="col-sm-10">
      				<p class="form-control-static">{{ student.first_name }}</p>
    			</div>
  			</div>
  			<div class="form-group">
    			<label class="col-sm-2 control-label">Second name</label>
    			<div class="col-sm-10">
      				<p class="form-control-static">{{ student.second_name }}</p>
    			</div>
  			</div>
  			<div class="form-group">
    			<label class="col-sm-2 control-label">Last name</label>
    			<div class="col-sm-10">
      				<p class="form-control-static">{{ student.last_name }}</p>
    			</div>
  			</div>
  			<div class="form-group">
    			<label class="col-sm-2 control-label">Date birth</label>
    			<div class="col-sm-10">
      				<p class="form-control-static">{{ student.birth }}</p>
    			</div>
  			</div>
  			<div class="form-group">
    			<label class="col-sm-2 control-label">Number</label>
    			<div class="col-sm-10">
      				<p class="form-control-static">{{ student.number }}</p>
    			</div>
  			</div>
  			<div class="form-group">
    			<label class="col-sm-2 control-label">First name</label>
    			<div class="col-sm-10">
      				<p class="form-control-static"><a href="{% url 'group_detail' pk=student.group.id %}">{{ student.group.title }}</a></p>
    			</div>
  			</div>
		</form>
	</div>
</div>
{% endblock %}

studentBASE/templates/studentBASE/student_form.html
{% extends 'studentBASE/base.html' %}
{% block menu %}
	<div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          	<li><a href="{% url 'group_list' %}">Groups</a></li>
          	<li  class="active"><a href="{% url 'student_list' %}">Students</a></li>
          	{% if not user.is_authenticated %}
                <li><a href="{% url 'login' %}">Login</a></li>
            {% else %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}
{% block content %}
<div class="container">
	<div class="row">
		<h1>Edit student</h1>
		
		<form method='POST' action=''  class="form-horizontal">{% csrf_token %}
   			<div class="form-group">
   				<label class="col-sm-2 control-label" for="id_first_name">First name:</label> 
   				<div class="col-sm-3">
   					<input  class="form-control" id="id_first_name" maxlength="50" name="first_name" type="text" value="{{ student.first_name }}"/>
   				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label"  for="id_second_name">Second name:</label> 
				<div class="col-sm-3">
					<input id="id_second_name" class="form-control" maxlength="50" name="second_name" type="text" value="{{ student.second_name }}"/>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="id_last_name">Last name:</label> 
				<div class="col-sm-3">
					<input id="id_last_name" class="form-control" maxlength="50" name="last_name" type="text" value="{{ student.last_name }}"/>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="id_birth">Birth (YYYY-MM-DD):</label> 
				<div class="col-sm-3">
					<input class="form-control" id="id_birth" name="birth" type="text" value="{{ student.birth }}"/>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="id_number">Number:</label> 
				<div class="col-sm-3">
					<input class="form-control" id="id_number" name="number" type="text" value="{{ student.number }}"/>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="id_group">Group:</label> 
				<div class="col-sm-3">
					<select class="form-control"  class="col-sm-2 control-label" id="id_group" name="group">
						<option value="">---------</option>
						{% for group in group_list %}
							<option value="{{ group.id }}" {% if student.group.id == group.id %}selected="selected"{% endif %}>{{ group.title }}</option>
						{% endfor %}
					</select></p>
				</div>
			</div>
   			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
   					<input type='Submit'  class="btn btn-info" value="Save" />
   				</div>
   			</div>
		</form>

	</div>
</div>
{% endblock %}

studentBASE/templates/studentBASE/student_form_custom.html
{% extends 'studentBASE/base.html' %}
{% block menu %}
	<div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          	<li><a href="{% url 'group_list' %}">Groups</a></li>
          	<li  class="active"><a href="{% url 'student_list' %}">Students</a></li>
          	{% if not user.is_authenticated %}
                <li><a href="{% url 'login' %}">Login</a></li>
            {% else %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}
{% block content %}
<form method='POST' action=''  class="form-horizontal">{% csrf_token %}
	<div class="form-group">
   		<label class="col-sm-2 control-label" for="id_first_name">First name:</label> 
   		<div class="col-sm-3">
   			<input  class="form-control" id="id_first_name" maxlength="50" name="first_name" type="text" />
   		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-2 control-label"  for="id_second_name">Second name:</label> 
		<div class="col-sm-3">
			<input id="id_second_name" class="form-control" maxlength="50" name="second_name" type="text" />
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-2 control-label" for="id_last_name">Last name:</label> 
		<div class="col-sm-3">
			<input id="id_last_name" class="form-control" maxlength="50" name="last_name" type="text" />
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-2 control-label" for="id_birth">Birth (YYYY-MM-DD):</label> 
		<div class="col-sm-3">
			<input class="form-control" id="id_birth" name="birth" type="text" />
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-2 control-label" for="id_number">Number:</label> 
		<div class="col-sm-3">
			<input class="form-control" id="id_number" name="number" type="text" />
		</div>
	</div>
	<input type="hidden" id="id_group" name="group" value="{{ group.id }}" />
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
   			<input type='Submit'  class="btn btn-info" value="Save"/>
   		</div>
	</div>
</form>
{% endblock %}

studentBASE/templates/studentBASE/student_list.html
{% extends 'studentBASE/base.html' %}
{% block menu %}
	<div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          	<li><a href="{% url 'group_list' %}">Groups</a></li>
          	<li class="active"><a href="{% url 'student_list' %}">Students</a></li>
          	{% if not user.is_authenticated %}
                <li><a href="{% url 'login' %}">Login</a></li>
            {% else %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}
{% block content %}
{% load studentBASE_extras %}
<div class="container">
	<div class="row">
		<h2>Students</h2>
		{% include "studentBASE/student_list_partial.html" %}
		<a href="{% url 'student_add' %}" class="btn btn-info">New</a>
	</div>
</div>
{% endblock %}

studentBASE/templates/studentBASE/student_list_partial.html
{% load studentBASE_extras %}
<table class="table table-hover">
	<thead>
	<tr>
		<th>Last name</th>
		<th>First name</th>
		<th>Second name</th>
		{% if show_group_name %}
			<th>Group</th>
		{% endif %}
		<th>Link to Admin</th>
	</tr>
</thead>
{% if student_list %}
	{% for student in student_list %}
		<tr>
			<td>
				<a href="{% url 'student_detail' pk=student.id %}">{{ student.last_name }}</a>
			</td>
			<td>
				{{ student.first_name }}
			</td>
			<td>
				{{ student.second_name }}
			</td>
			{% if show_group_name %}
				<td>
					<a href="{% url 'group_detail' student.group.id %}">{{ student.group.title }}</a>
				</td>
			{% endif %}
			<td>
				<a href="{% edit student %}">[To Admin]</a>
			</td>
		</tr>
	{% endfor %}
{% else %}
	<tr>
		<td>
			No students
		</td>
	</tr>
{% endif %}
</table>